export { buildPlanView, deckPurposeLabel, formatSlideRange, parseEvidenceRef, plannedVisual, slideIdea, slideSources } from './lib/plan'
export type { PlanRow, PlanSectionSummary, PlanStats, PlanView, SlideSource } from './lib/plan'
export { DeckPlanView } from './ui/DeckPlanView'
export type { PlanEditor } from './ui/DeckPlanView'
export { PLAN_EDIT_SOON, SoonButton } from './ui/SoonButton'
