# generated by datamodel-codegen:
#   filename:  audit-issue.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Severity(Enum):
    info = 'info'
    warning = 'warning'
    error = 'error'
    blocker = 'blocker'


class Bbox(BaseModel):
    x: float | None = None
    y: float | None = None
    w: float | None = None
    h: float | None = None


class Kind(Enum):
    geometry = 'geometry'
    style = 'style'
    text = 'text'
    model_verdict = 'model_verdict'
    source_span = 'source_span'
    package = 'package'


class EvidenceItem(BaseModel):
    kind: Kind | None = None
    ref: str | None = None
    detail: str | None = None


class Status(Enum):
    open = 'open'
    selected = 'selected'
    fixed = 'fixed'
    dismissed = 'dismissed'
    unresolved = 'unresolved'


class Provenance(BaseModel):
    rule_version: str | None = None
    model_id: str | None = None
    prompt_version: str | None = None


class AuditIssue(BaseModel):
    schema_version: str
    id: str
    audit_run_id: str
    deck_revision: int | None = None
    rule_code: str
    deterministic: bool
    severity: Severity
    slide_id: str | None = None
    slide_index: int | None = None
    shape_ids: list[str] | None = None
    bbox: Bbox | None = None
    message: str
    measured_value: str | float | None = None
    threshold: str | float | None = None
    evidence: list[EvidenceItem] | None = None
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    status: Status
    repairable: bool
    proposed_actions: list[str] | None = None
    provenance: Provenance | None = None
