# generated by datamodel-codegen:
#   filename:  content-pack.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Kind(Enum):
    paragraph = 'paragraph'
    list = 'list'
    quote = 'quote'
    code = 'code'
    table_ref = 'table_ref'
    image_ref = 'image_ref'
    chart_ref = 'chart_ref'
    diagram_ref = 'diagram_ref'
    note = 'note'


class Kind1(Enum):
    image = 'image'
    icon = 'icon'
    logo = 'logo'
    screenshot = 'screenshot'
    diagram = 'diagram'


class Asset(BaseModel):
    id: str
    kind: Kind1
    artifact_id: str
    caption: str | None = None
    alt: str | None = None
    width_px: int | None = None
    height_px: int | None = None
    license: str | None = None
    attribution: str | None = None
    source_url: str | None = None


class CharSpan(BaseModel):
    start: int | None = None
    end: int | None = None


class SourceRef(BaseModel):
    artifact_id: str
    page: int | None = None
    sheet: str | None = None
    range: str | None = None
    heading_path: list[str] | None = None
    char_span: CharSpan | None = None


class Block(BaseModel):
    kind: Kind
    text: str | None = None
    items: list[str] | None = None
    source_ref: SourceRef


class Section(BaseModel):
    id: str
    heading: str
    level: int | None = None
    blocks: list[Block]


class Table(BaseModel):
    id: str
    title: str | None = None
    headers: list[str]
    rows: list[list[str | float | None]]
    units: dict[str, str] | None = None
    source_ref: SourceRef


class ChartSeries(BaseModel):
    name: str | None = None
    values: list[float]


class Chart(BaseModel):
    id: str
    categories: list[str]
    series: list[ChartSeries]
    source_ref: SourceRef


class Diagram(BaseModel):
    """Simple flow/step diagram — steps rendered as SmartArt-like
    grouped editable shapes (AGENTS.md baseline, not real dgm)."""

    id: str
    steps: list[str]
    source_ref: SourceRef


class Warning(BaseModel):
    code: str
    message: str
    source_ref: SourceRef | None = None


class ContentPack(BaseModel):
    schema_version: str
    id: str
    language: str
    title_hint: str | None = None
    sections: list[Section]
    tables: list[Table]
    charts: list[Chart] = []
    diagrams: list[Diagram] = []
    assets: list[Asset]
    warnings: list[Warning]
