# generated by datamodel-codegen:
#   filename:  deck-plan.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Brief(BaseModel):
    purpose: str
    audience: str
    language: str
    target_slide_count: Annotated[int, Field(ge=3, le=40)]
    tone: str | None = None
    mandatory_sections: list[str] | None = None
    forbidden_claims: list[str] | None = None


class Section(BaseModel):
    id: str
    title: str
    slide_ids: list[str]


class Provenance(BaseModel):
    planner: str
    prompt_version: str
    schema_version: str
    model_id: str | None = None
    input_hashes: list[str] | None = None


class Purpose(Enum):
    title = 'title'
    agenda = 'agenda'
    section_divider = 'section_divider'
    overview = 'overview'
    problem = 'problem'
    solution = 'solution'
    benefits = 'benefits'
    data = 'data'
    comparison = 'comparison'
    timeline = 'timeline'
    process = 'process'
    quote = 'quote'
    team = 'team'
    cta = 'cta'
    qa = 'qa'
    thank_you = 'thank_you'
    custom = 'custom'


class Kind(Enum):
    title = 'title'
    subtitle = 'subtitle'
    bullet = 'bullet'
    paragraph = 'paragraph'
    number = 'number'
    label = 'label'
    image = 'image'
    icon = 'icon'
    table = 'table'
    chart = 'chart'
    diagram = 'diagram'
    quote = 'quote'
    note = 'note'


class ChartType(Enum):
    bar = 'bar'
    line = 'line'
    pie = 'pie'
    area = 'area'
    scatter = 'scatter'


class ChartSpec(BaseModel):
    chart_type: ChartType | None = None
    series_count: Annotated[int | None, Field(le=5)] = None
    has_axis_labels: bool | None = None
    has_units: bool | None = None
    has_legend: bool | None = None


class ContentUnit(BaseModel):
    role: str
    kind: Kind
    text: str | None = None
    evidence_ids: list[str] | None = None
    target_chars: int | None = None
    asset_ref: str | None = None
    table_ref: str | None = None
    chart_ref: str | None = None
    diagram_ref: str | None = None
    chart_spec: ChartSpec | None = None


class DesiredVisual(Enum):
    none = 'none'
    image = 'image'
    icon_set = 'icon_set'
    chart = 'chart'
    table = 'table'
    diagram = 'diagram'
    screenshot = 'screenshot'
    quote = 'quote'


class Level(Enum):
    sparse = 'sparse'
    medium = 'medium'
    dense = 'dense'


class DensityBudget(BaseModel):
    level: Level
    max_items: int | None = None
    max_chars: int | None = None


class SlidePlan(BaseModel):
    id: str
    index: int
    purpose: Purpose
    title_intent: Annotated[
        str, Field(description='conclusion-style title, not a topic')
    ]
    key_message: str
    evidence_ids: Annotated[list[str], Field(min_length=1)]
    content_units: list[ContentUnit]
    desired_visual: DesiredVisual | None = None
    density_budget: DensityBudget
    speaker_note: str | None = None
    mandatory: bool | None = None


class DeckPlan(BaseModel):
    schema_version: str
    id: str
    brief: Brief
    evidence_graph_id: str
    objective: str
    audience: str
    language: str
    sections: list[Section] | None = None
    slides: Annotated[list[SlidePlan], Field(min_length=1)]
    provenance: Provenance
