# generated by datamodel-codegen:
#   filename:  design-dna.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field
from typing_extensions import TypeAliasType


class SlideSize(BaseModel):
    width_emu: int
    height_emu: int
    aspect_ratio: float


ColorsAdditionalProperty = TypeAliasType(
    "ColorsAdditionalProperty", Annotated[str, Field(pattern='^[0-9A-Fa-f]{6}$')]
)


class Theme(BaseModel):
    part: str
    major_font: str
    minor_font: str
    colors: dict[str, ColorsAdditionalProperty]


class FontSize(BaseModel):
    size_pt: float
    frequency: int
    roles: list[str]


class Spacing(BaseModel):
    common_margins_emu: list[int] | None = None
    common_gaps_emu: list[int] | None = None
    alignment_lines_x: list[int] | None = None
    alignment_lines_y: list[int] | None = None


class Kind(Enum):
    solid = 'solid'
    gradient = 'gradient'
    image = 'image'
    pattern = 'pattern'
    inherit = 'inherit'


class Background(BaseModel):
    kind: Kind | None = None
    value: str | None = None
    frequency: int | None = None


class Kind1(Enum):
    logo = 'logo'
    footer = 'footer'
    page_number = 'page_number'
    date = 'date'
    watermark = 'watermark'


class SlideRole(BaseModel):
    role: str
    slide_ids: list[str]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    evidence: str | None = None


class Mutability(Enum):
    fully_editable = 'fully_editable'
    partially_editable = 'partially_editable'
    preserve_only = 'preserve_only'


class Exemplar(BaseModel):
    slide_index: int
    part: str
    role: str
    cluster_id: str
    layout_part: str | None = None
    preview_artifact_id: str | None = None
    mutability: Mutability | None = None


class Cardinality(BaseModel):
    min: int | None = None
    max: int | None = None
    observed: int | None = None


class Kind2(Enum):
    text = 'text'
    number = 'number'
    image = 'image'
    icon = 'icon'
    chart = 'chart'
    table = 'table'
    label = 'label'


class Slot(BaseModel):
    role: str
    kind: Kind2
    max_chars: int | None = None


class Component(BaseModel):
    id: str
    semantic_role: str
    source_slide: str
    shape_ids: list[str]
    cardinality: Cardinality | None = None
    slots: list[Slot] | None = None


class OccupancyRange(BaseModel):
    min: float | None = None
    max: float | None = None


class Capacities(BaseModel):
    max_title_chars: int | None = None
    max_body_chars: int | None = None
    max_bullets: int | None = None
    max_words_per_bullet: int | None = None
    max_table_rows: int | None = None
    max_table_cols: int | None = None
    max_chart_series: int | None = None
    occupancy_range: OccupancyRange | None = None


class Strategy(Enum):
    preserve = 'preserve'
    immutable_decoration = 'immutable_decoration'
    raster_fallback = 'raster_fallback'
    skip = 'skip'


class UnsupportedFeature(BaseModel):
    feature: str
    location: str
    strategy: Strategy
    disclosure: str | None = None


class Bbox(BaseModel):
    x: float
    y: float
    w: float
    h: float


class Placeholder(BaseModel):
    type: str
    idx: int | None = None
    bbox: Bbox | None = None


class Frequency(BaseModel):
    value: str
    frequency: int
    contexts: list[str] | None = None


class Master(BaseModel):
    part: str
    layout_parts: list[str]
    placeholders: list[Placeholder]


class Layout(BaseModel):
    part: str
    name: str
    type: str
    matching_name: str | None = None
    placeholders: list[Placeholder]


class Declared(BaseModel):
    themes: list[Theme]
    masters: list[Master]
    layouts: list[Layout]


class Observed(BaseModel):
    fonts: list[Frequency]
    font_sizes: list[FontSize]
    colors: list[Frequency]
    spacing: Spacing
    backgrounds: list[Background] | None = None


class Anchor(BaseModel):
    kind: Kind1
    bbox: Bbox
    slide_coverage: Annotated[float, Field(ge=0.0, le=1.0)]
    source_parts: list[str] | None = None


class DesignDNA(BaseModel):
    schema_version: str
    template_id: str
    analysis_id: str
    created_at: AwareDatetime
    slide_size: SlideSize
    declared: Declared
    observed: Observed
    anchors: list[Anchor]
    slide_roles: list[SlideRole]
    exemplars: list[Exemplar]
    components: list[Component]
    capacities: Capacities
    unsupported_features: list[UnsupportedFeature]
