# generated by datamodel-codegen:
#   filename:  evidence-graph.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Type(Enum):
    claim = 'claim'
    number = 'number'
    entity = 'entity'
    section = 'section'
    table = 'table'
    visual = 'visual'
    source_span = 'source_span'


class Value(BaseModel):
    raw: str | None = None
    numeric: float | None = None
    unit: str | None = None


class SourceRef(BaseModel):
    artifact_id: str
    page: int | None = None
    sheet: str | None = None
    range: str | None = None


class Node(BaseModel):
    id: str
    type: Type
    text: str | None = None
    value: Value | None = None
    source_ref: SourceRef
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Type1(Enum):
    supports = 'supports'
    derived_from = 'derived_from'
    illustrates = 'illustrates'
    contrasts = 'contrasts'
    belongs_to = 'belongs_to'


class Edge(BaseModel):
    from_: Annotated[str, Field(alias='from')]
    to: str
    type: Type1
    weight: float | None = None


class EvidenceGraph(BaseModel):
    schema_version: str
    id: str
    content_pack_id: str
    nodes: list[Node]
    edges: list[Edge]
