# generated by datamodel-codegen:
#   filename:  quality-passport.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field


class Inputs(BaseModel):
    template_sha256: str
    template_name: str | None = None
    content_pack_id: str
    brief_hash: str


class Validity(BaseModel):
    opens_cleanly: bool | None = None
    ooxml_errors: int | None = None
    round_trip_ok: bool | None = None


class Editability(BaseModel):
    pei_level: Annotated[int | None, Field(ge=0, le=5)] = None
    native_text_ratio: float | None = None
    raster_only_slides: int | None = None
    preserved_unsupported_objects: int | None = None


class StyleFidelity(BaseModel):
    palette_compliance: float | None = None
    font_compliance: float | None = None
    layout_origin_compliance: float | None = None
    anchor_compliance: float | None = None


class ContentSupport(BaseModel):
    supported_claims: int | None = None
    unsupported_claims: int | None = None
    numbers_verified: int | None = None
    numbers_failed: int | None = None


class Readability(BaseModel):
    contrast_failures: int | None = None
    overflow_count: int | None = None
    avg_occupancy: float | None = None


class PerStageItem(BaseModel):
    stage: str
    seconds: float
    cached: bool | None = None


class Timings(BaseModel):
    total_seconds: float | None = None
    per_stage: list[PerStageItem] | None = None


class PerModelItem(BaseModel):
    model_id: str | None = None
    calls: int | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None


class Usage(BaseModel):
    total_tokens: int | None = None
    model_calls: int | None = None
    per_model: list[PerModelItem] | None = None


class Metrics(BaseModel):
    validity: Validity
    editability: Editability
    style_fidelity: StyleFidelity | None = None
    content_support: ContentSupport | None = None
    readability: Readability | None = None
    timings: Timings
    usage: Usage | None = None


class IssuesSummary(BaseModel):
    blocker: int | None = None
    error: int | None = None
    warning: int | None = None
    info: int | None = None
    fixed: int | None = None
    dismissed: int | None = None
    unresolved: int | None = None


class Fallback(BaseModel):
    feature: str | None = None
    slide_index: int | None = None
    strategy: str | None = None
    disclosure: str | None = None


class ModelProfile(BaseModel):
    model_id: str | None = None
    provider: str | None = None
    size_b: float | None = None
    license: str | None = None


class Provenance(BaseModel):
    pipeline_version: str
    skill_version: str | None = None
    prompt_versions: dict[str, str]
    model_profiles: list[ModelProfile]
    config_hashes: dict[str, str]
    seed: int | None = None


class Format(Enum):
    pptx = 'pptx'
    pdf = 'pdf'
    html = 'html'


class Export(BaseModel):
    format: Format
    artifact_id: str
    sha256: str
    size_bytes: int | None = None


class QualityPassport(BaseModel):
    schema_version: str
    run_id: str
    variant_id: str | None = None
    generated_at: AwareDatetime
    inputs: Inputs
    metrics: Metrics
    issues_summary: IssuesSummary
    fallbacks: list[Fallback] | None = None
    provenance: Provenance
    exports: list[Export]
