# generated by datamodel-codegen:
#   filename:  skill-manifest.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Tool(BaseModel):
    name: str
    description: str
    input_schema: str
    output_schema: str
    timeout_seconds: int
    idempotent: bool
    retryable: bool | None = None


class Kind(Enum):
    file = 'file'
    directory = 'directory'
    text = 'text'
    config = 'config'
    credentials = 'credentials'


class Input(BaseModel):
    name: str
    kind: Kind
    required: bool | None = None
    media_types: list[str] | None = None


class Kind1(Enum):
    file = 'file'
    report = 'report'
    events = 'events'


class Output(BaseModel):
    name: str
    kind: Kind1
    media_types: list[str] | None = None


class Network(Enum):
    none = 'none'
    provider_only = 'provider_only'
    open = 'open'


class Requirements(BaseModel):
    container: bool | None = None
    network: Network | None = None
    system_tools: list[str] | None = None
    env_vars: list[str] | None = None


class Capabilities(BaseModel):
    streaming_events: bool | None = None
    resume: bool | None = None
    cancel: bool | None = None


class SkillManifest(BaseModel):
    schema_version: str
    id: str
    name: str
    version: str
    description: str | None = None
    license: str | None = None
    tools: list[Tool]
    inputs: list[Input]
    outputs: list[Output]
    requirements: Requirements
    capabilities: Capabilities | None = None
