# generated by datamodel-codegen:
#   filename:  variant-spec.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class Strategy(Enum):
    faithful = 'faithful'
    balanced = 'balanced'
    visual = 'visual'
    custom = 'custom'


class Primary(Enum):
    layout_choice = 'layout_choice'
    density = 'density'
    ordering = 'ordering'
    visualization_emphasis = 'visualization_emphasis'
    typography_weight = 'typography_weight'


class DifferenceAxis(BaseModel):
    primary: Primary
    description: str


class Weights(BaseModel):
    exemplar_fidelity: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    visual_density: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    text_density: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    chart_preference: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    novelty: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Density(Enum):
    sparse = 'sparse'
    medium = 'medium'
    dense = 'dense'


class SlideOverride(BaseModel):
    slide_plan_id: str | None = None
    preferred_exemplar_ids: list[str] | None = None
    preferred_visual: str | None = None
    density: Density | None = None


class VariantSpec(BaseModel):
    schema_version: str
    id: str
    strategy: Strategy
    difference_axis: DifferenceAxis
    invariant_evidence_ids: Annotated[
        list[str], Field(description='All variants must cover the same evidence set.')
    ]
    weights: Weights
    slide_overrides: list[SlideOverride] | None = None
    seed: int
    config_version: str | None = None
